language: cpp
sudo: required
compiler: gcc
# works on Precise and Trusty
os: linux
script:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-cpp-3.11.4.tar.gz
  - tar -xzvf protobuf-cpp-3.11.4.tar.gz
  - pushd protobuf-3.11.4 && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig && popd
  - ls -l /usr/local/include
  - sudo bash ./build.sh
env:
  - MATRIX_EVAL="CC=gcc-7.5 && CXX=g++-7.5"
